config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services

    root to: "users#index"
  end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => '/sidekiq'
    end

  resources :events
  get 'events/:id/RSVP', to: 'events#join', as: 'join_event'
  delete 'events/:id/RSVP', to: 'events#leave', as: 'leave_event'

  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'events#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :creator, :class_name => "User"
	has_many :event_attendees, :foreign_key => "attended_event_id", :class_name => "EventAttendee"
	has_many :attendees, :through => :event_attendees, source: "attendee"
	
	scope :upcoming, lambda { where("#{:date} >= ?" , Date.current) }
	scope :past, lambda { where("#{:date} < ?" , Date.current) }

	default_scope -> { order(:date) }
	
	validates :title, presence: true, length: { maximum: 25 }
	validates :date, presence: true
	validate :is_event_date_past

	def is_event_date_past
	  errors.add(:date, "can't be in the past") if is_past_event?
	end

	def is_past_event?
		date < Date.current
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :set_event, only: [:show, :edit, :update, :destroy, :leave, :join]
  before_action :authorize, only: [:new, :create, :edit, :update, :destroy, :leave, :join]

	def index
	  @events = Event.all
	end

	def show
	  @users = @event.attendees
	end

	def new
	  @event = Event.new
	end

	def edit
	end

	def create
	  @event = current_user.created_events.build(event_params)
	  if @event.save
	    redirect_to @event
	  else
	    render :new
	  end
	end

	def update
	  if @event.update(event_params)
	    redirect_to @event
	  else
	    render :edit
	  end
	end

	def destroy
	  @event.destroy
	  redirect_to events_url
	end

	def join
	  @event.attendees << current_user
	  redirect_back(fallback_location: root_path)
	end

	def leave
	  @event.attendees.delete(current_user)
	  redirect_back(fallback_location: root_path)
	end

	private
	  def set_event
	    @event = Event.find(params[:id])
	  end

	  def authorize
	    redirect_to(root_url) if current_user.nil?
	  end

	  def event_params
	    params.require(:event).permit(:title, :description, :date)
	  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<li class="event ">
  <div class="title-block">
   <h3>  <%= link_to "#{event.title.nil? ? "Event" : event.title}", event_path(event) %>
    <h4> <%= event.date.year == Date.current.year ? event.date.to_formatted_s(:short) : event.date.to_formatted_s(:long) %></h4>
    
    <% if current_user == event.creator %>
      <%= link_to 'Edit', edit_event_path(event) %> |
      <%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' } %></td> |
    <% end %>
    
    <% if event.attendees.find_by(id: current_user) %>
      <%= link_to 'Leave', leave_event_path(event), method: :delete %>
    <% elsif !current_user.nil? and !event.is_past_event? %>
      <%= link_to 'Join', join_event_path(event) %>
    <% end %>
  </div>
  <p> <%= event.description %></p>
</li>

app/views/events/_form.html.erb
<% if event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

    <ul>
    <% event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% provide(:title, "Create Event") %>
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <div class="well well-lg">
      <%= form_for(@event) do |f| %>

        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", autofocus: true %>

        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control", :size => "20x5" %>

        <div class="row">

          <div class="col-sm-4">
            <%= f.label "Date" %>
            <div class="input-group date">
              <%= f.date_field :date, class: "form-control" %><span class="input-group-addon"></span>
            </div>
          </div>

        </div>

        <div class="row create-bottom">
          <div class="col-sm-4 col-sm-offset-4">
            <%= f.submit "Submit", class: "form-control btn btn-success create-button"%>  
          </div>
        </div>

      <% end %>
      
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'All Events', events_path %>

app/views/events/index.html.erb
<h1>Events</h1>

<h2> Upcoming Events </h2>
<ul class="events">
  <%= render @events.upcoming %>
</ul>

<h2> Past Events </h2>
<ul class="events">
  <%= render @events.past %>
</ul>

app/views/events/new.html.erb
<%= link_to 'Home>', root_path %>
<h2>Create a New Event</h2>
<%= render 'form', event: @event %>

app/views/events/show.html.erb
<%= render @event %>
  <table>
    <th> Attendees</th>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  <table>